variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - apk add -U make doxygen
  - pip install -U sphinx
  - pip install -U sphinx-rtd-theme
  - pip install -U breathe
  - sphinx-build -b html doc/ public
  artifacts:
    paths:
    - public
  only:
  - devel
