[project]
name = "nfbtools"
version = "0.2.0"
dependencies = ["pyyaml"]

[project.scripts]
nfb-meter = "nfbmeter.nfbmeter:main"
nfb-bootstrap = "nfbbootstrap.nfb_bootstrap:main"

[tool.setuptools]
packages = [
	"nfbmeter",
	"nfbbootstrap",
]
