# SPDX-License-Identifier: GPL-2.0
#
# Makefile for NFB driver
#
# Copyright (C) 2017-2022 CESNET
#
# Author(s):
#   Martin Spinler <spinler@cesnet.cz>

include $(DRIVER_TOPDIR)/Makefile.conf

obj-$(CONFIG_NFB)       += nfb/

# The nfb-xvc now uses the libpci and doesn't needs xvc kernel driver anymore.
#obj-$(CONFIG_NFB_XVC)   += xvc/
